from carbentra_tools import FREECAD_LIB, FONT_REGULAR, PYTHON, kicad_resource
from pathlib import Path
import json,hashlib,re,subprocess,shutil,datetime,os
R=Path(__file__).resolve().parents[1];V=R/'validation'
# Version control retains prior evidence; do not create duplicate working-tree archives.
def run(args):subprocess.run(args,cwd=R,check=True,stdout=subprocess.DEVNULL)
run(['kicad-cli','pcb','drc',str(R/'integrated.kicad_pcb'),'--format','json','-o',str(V/'final_drc.json')])
run(['kicad-cli','sch','erc',str(R/'integrated.kicad_sch'),'--format','json','-o',str(V/'final_erc.json')])
for name in ['final_drc.json','final_erc.json']:
 path=V/name;path.write_text(json.dumps(json.loads(path.read_text(encoding='utf-8')),indent=2)+'\n',encoding='utf-8',newline='\n')
for script in('verify_schematic.py','audit_pcb_pins.py','audit_isolation.py'):run([PYTHON,str(R/'scripts'/script)])
for a,z in [('pcb_pin_audit.json','final_pin_audit.json'),('projected_isolation.json','final_isolation.json'),('independent_schematic_checks.json','final_source_graph.json')]:shutil.copyfile(V/a,V/z)
shutil.copyfile(V/'final_drc.json',V/'drc.json');shutil.copyfile(V/'final_erc.json',V/'erc.json')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();board=R/'integrated.kicad_pcb';d=json.loads((V/'final_drc.json').read_text(encoding='utf-8'));e=json.loads((V/'final_erc.json').read_text(encoding='utf-8'));counts={'violations':len(d['violations']),'unconnected':len(d['unconnected_items']),'footprint_errors':len(d.get('schematic_parity',[]))};erc_messages=[v for sheet in e['sheets'] for v in sheet['violations']];erc={'messages':len(erc_messages),'errors':sum(v['severity']=='error' for v in erc_messages),'warnings':sum(v['severity']=='warning' for v in erc_messages)};iso=json.loads((V/'final_isolation.json').read_text(encoding='utf-8'));pin=json.loads((V/'final_pin_audit.json').read_text(encoding='utf-8'));native=json.loads((V/'rule_controls/result.json').read_text(encoding='utf-8'));negative=json.loads((V/'rule_controls/projected_negative.json').read_text(encoding='utf-8'))
assert not any(counts.values()) and not any(erc.values()) and iso['pass'] and pin['status']=='PASS' and native['pass'] and not negative['pass']
summary={'status':'DIGITAL CHECKS PASS / DEVELOPMENT HOLD','generated_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'board_sha256':sha(board),'rules_sha256':sha(board.with_suffix('.kicad_dru')),'schematic_files_sha256':{p.name:sha(p)for p in sorted(R.glob('*.kicad_sch'))},'main_electrical_items':101,'physical_component_bodies':99,'zero_height_test_pads':2,'mechanical_mounting_footprints':4,'main_numbered_pad_keys':pin['numbered_pad_keys'],'assembly_numbered_terminals':348,'layer_count':4,'native_DRC':counts,'ERC':erc,'projected_isolation':{'minimum_mm':iso['minimum_mm'],'limiting_pair':iso['minimum_pair'],'routing_items_below_8p4_mm':len(iso['routing_margin_below_8p4']),'scope':iso['basis']},'negative_controls':{'native_supported_rule_rejects_6mm_gap':native['supported']['expected_rule_reported'],'old_unsupported_rule_did_not_reject_6mm_gap':not native['unsupported']['expected_rule_reported'],'independent_checker_rejects_shifted_hot_pad':not negative['pass']},'authoritative_reports':['final_drc.json','final_erc.json','final_pin_audit.json','final_isolation.json','final_source_graph.json'],'not_proven':['manufactured clearances/creepage and insulation','16 A continuous thermal rating or motor/inrush switching suitability','fuse total-clearing coordination and fault containment','measurement accuracy/calibration, EMC, RF, production reliability','physical thermal response and sensor/fault coverage','certification or permission to fabricate/energize']}
rear_path=V/'rear_termination.json'
if rear_path.exists():
 rear=json.loads(rear_path.read_text(encoding='utf-8'));assert rear['inputs']['electronics/rev_b/integrated/integrated.kicad_pcb']==sha(board) and rear['pass_nominal_margin']
 summary['rear_termination_3D']={'report':'rear_termination.json','minimum_mm':min(x['minimum_mm']for x in rear['minimums']),'target_mm':8.4,'scope':'Rear L/N blades and bare input-link starts versus isolated pads, tracks, vias and conservative plane outline; full assembly audit is separate'}
 summary['authoritative_reports'].append('rear_termination.json')
(V/'final_summary.json').write_text(json.dumps(summary,indent=2), encoding='utf-8', newline='\n');print(json.dumps(summary,indent=2))
